# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

after_success:
  - R CMD INSTALL . # install the package so we can use it to
  - Rscript R/_render.R # render the output samples

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
